### ISSUE TITLE
Code Release of Scannet Dataset

### ISSUE THREAD

**Issue by Arimkyie** [fudan-zvg/DG-SLAM#6]
Hi, I have tried to test the SLAM performance on real-world static sequences of TUM and ScanNet.  

I attempted to write the yaml file for fr1_room, set the correct camera intrinsic parameters, and removed the image distortion. However, the test results were not ideal. 

![Image](https://github.com/user-attachments/assets/61c9ab98-af2a-4422-a7bb-da87cb4e85f1)

At the same time, I tried to add the code for loading the Scannet dataset and tested the scene0207_00 sequence, setting the tracking and mapping iterations to 100 and 200 respectively. But the results were still not ideal. Could you provide your test code and experimental parameter configuration on Scannet?

![Image](https://github.com/user-attachments/assets/086ce702-48de-46a8-aeab-47127f7b193d)

**Comment by Arimkyie** [comment]
There is my intrinsic parameters of fr1_room and scene0207_00. And I use `cv2.initUndistortRectifyMap` to remove the image distortion. The other patameters are the default settings in `tum.yaml` and 'dg_slam.yaml' except I change the tracking iters and mapping iters to 100 and 200 in the code.
```
scene: rgbd_dataset_freiburg1_room
inherit_from: configs/TUM_RGBD/tum.yaml
config_path: configs/TUM_RGBD/rgbd_dataset_freiburg1_room.yaml
data:
  output: output/TUM_RGBD/rgbd_dataset_freiburg1_room
  exp_name: test
cam:  
  H: 480 
  W: 640 
  fx: 517.306408
  fy: 516.469215
  cx: 318.643040
  cy: 255.313989
  k1: 0.262383
  k2: -0.953104
  p1: -0.005358
  p2: 0.002628
  k3: 1.163314
  distorted: True
```
```
scene: scene0207_00
inherit_from: configs/Scannet/scannet.yaml
config_path: configs/Scannet/scene0207_00.yaml
data:
  output: output/Scannet/scene0207_00
  exp_name: test
cam:  
  H: 480 
  W: 640 
  fx: 577.590617284
  fy: 578.729752066
  cx: 318.904938272
  cy: 242.683471074
  k1: 0
  k2: 0
  p1: 0
  p2: 0
  k3: 0
  distorted: False
```
